### PR TITLE
Change the path instruction

### PR DESCRIPTION
**Pull request by CodeFerriCode**
- Change the path separator in the existing path to backslash as what is used in windows path.
- Add path that works on newer versions of Windows system.

### CODE REVIEW

**Comment by Phuurl** [comment]
Hey @CodeFerriCode, do you know what versions that `shell:appdata\MobaXterm` shortcut works for? Just tried it on my PC with W10 21H1 and MobaXterm 20.6 and it didn't resolve

**Comment by CodeFerriCode** [comment]
Hi @Phuurl, the setting works for me is MobaXterm Personal Edition v9.3 and Microsoft Windows 10 Enterprise 10.0.18363 Build 18363.
And the resolved path is `C:\Users\<my_user_name>\AppData\Roaming\MobaXterm`.

**Comment by Phuurl** [comment]
Interesting, have you installed MobaXterm at user level rather than system? Not sure why they'd be different across two installs - may be worth rephrasing it to say it could be in either location just so people don't go for the newer location and get confused if it doesn't resolve

**Comment by Phuurl** [comment]
@CodeFerriCode I've just updated the PR slightly to make it clearer that it could be in either location - look good to you?

**Comment by CodeFerriCode** [comment]
@Phuurl Yes, it looks good. I was not able to edit my PR after my last comment. Thanks for helping with the improved path info.

And I dont know why mine Mobaxterm's ini is in AppData.

**Comment by Phuurl** [comment]
No worries - thanks for the contribution 😀

**Review by Phuurl — APPROVED** [review]

**Comment by CodeFerriCode** [comment]
How will the submodule info in https://github.com/dracula/dracula-theme be updated?

**Comment by Phuurl** [comment]
Good shout - I've just opened https://github.com/dracula/dracula-theme/pull/614 to get it synced over 👍

**Pull request merged**
